// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_pc,0,0);
        VL_IN8(wen_pc,0,0);
        CData/*1:0*/ top__DOT__M_wlen;
        CData/*1:0*/ top__DOT__M_rlen;
        CData/*1:0*/ top__DOT__Branch;
        CData/*0:0*/ top__DOT__isB_type;
        CData/*1:0*/ top__DOT__RegIn;
        CData/*0:0*/ top__DOT__ALUIn1Sel;
        CData/*0:0*/ top__DOT__ALUIn2Sel;
        CData/*0:0*/ top__DOT__R_wen;
        CData/*0:0*/ top__DOT__M_wen;
        CData/*0:0*/ top__DOT__M_ren;
        CData/*0:0*/ top__DOT__ebreak;
        CData/*0:0*/ top__DOT__u2__DOT__EandCSR;
        CData/*4:0*/ top__DOT__u2__DOT__rs1;
        CData/*1:0*/ top__DOT__u2__DOT__u0__DOT__BranchEnc__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u2__DOT__u0__DOT__BranchEnc__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u2__DOT__u0__DOT__isB_typeEnc__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u2__DOT__u0__DOT__isB_typeEnc__DOT__i0__DOT__hit;
        CData/*1:0*/ top__DOT__u2__DOT__u0__DOT__RegInEnc__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u2__DOT__u0__DOT__RegInEnc__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u2__DOT__u0__DOT__ALUIn1SelEnc__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u2__DOT__u0__DOT__ALUIn1SelEnc__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u2__DOT__u0__DOT__ALUIn2SelEnc__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u2__DOT__u0__DOT__ALUIn2SelEnc__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u2__DOT__u0__DOT__R_wenEnc__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u2__DOT__u0__DOT__R_wenEnc__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u2__DOT__u0__DOT__M_renEnc__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u2__DOT__u0__DOT__M_renEnc__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u2__DOT__u0__DOT__M_wenEnc__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u2__DOT__u0__DOT__M_wenEnc__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u2__DOT__u0__DOT__EandCSREnc__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u2__DOT__u0__DOT__EandCSREnc__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u2__DOT__u1__DOT__u0__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u2__DOT__u1__DOT__u0__DOT__i0__DOT__hit;
        CData/*4:0*/ top__DOT__u2__DOT__u2__DOT__u0__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u2__DOT__u2__DOT__u0__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u2__DOT__u2__DOT__u1__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u3__DOT__ALUIn1MUX__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u3__DOT__ALUIn2MUX__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__isM;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__ADDSUB;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__ADDSUBSuben;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__COMP;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__ADDEROverflow;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT____Vcellout__COMPResultMUX__out;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__SHIFT;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__SHIFTfunct3;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__LOGIC;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__LOGICfunct3;
        CData/*5:0*/ top__DOT__u3__DOT__ALU__DOT__u0__DOT__i0__DOT__lut;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__u0__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__u0__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__SUBMux__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__u1__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__u1__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__ADDERIn2MUX__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__COMPResultMUX__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__COMPResultMUX__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__u2__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__u2__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__shift_fillbit;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u0__DOT__i0__DOT__lut_out;
    };
    struct {
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u0__DOT__i0__DOT__hit;
        CData/*1:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u1__DOT__i0__DOT__key;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u1__DOT__i0__DOT__hit;
        CData/*1:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u2__DOT__i0__DOT__key;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u2__DOT__i0__DOT__hit;
        CData/*1:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u3__DOT__i0__DOT__key;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u3__DOT__i0__DOT__hit;
        CData/*1:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u4__DOT__i0__DOT__key;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u4__DOT__i0__DOT__hit;
        CData/*1:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u5__DOT__i0__DOT__key;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u5__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__u3__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__u3__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__LogicModule__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u3__DOT__ALU__DOT__ResultMux__DOT__i0__DOT__hit;
        CData/*1:0*/ top__DOT__u3__DOT__M_rlenMUX__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u3__DOT__M_rlenMUX__DOT__i0__DOT__hit;
        CData/*1:0*/ top__DOT__u3__DOT__M_wlenMUX__DOT__i0__DOT__lut_out;
        CData/*0:0*/ top__DOT__u3__DOT__M_wlenMUX__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u3__DOT__M_rdataMUX__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u3__DOT__RegInMUX__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u3__DOT__BranchMUX__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u5__DOT__u0__DOT__i0__DOT__hit;
        CData/*0:0*/ top__DOT__u5__DOT__u1__DOT__i0__DOT__hit;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_1;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_26;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_28;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_29;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_30;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_pc__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        VL_IN(d_init_pc,31,0);
        IData/*31:0*/ top__DOT__inst;
        IData/*31:0*/ top__DOT__pc;
        IData/*31:0*/ top__DOT__M_rdata;
        IData/*31:0*/ top__DOT__imm;
        IData/*31:0*/ top__DOT__dst;
        IData/*31:0*/ top__DOT__dnpc;
        IData/*31:0*/ top__DOT__u0__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ top__DOT__u1__DOT____VlemCond_1;
        IData/*31:0*/ top__DOT__u1__DOT____VlemCall_0__vaddr_ifetch;
        VlWide<11>/*350:0*/ top__DOT__u2__DOT__u2__DOT__u1__DOT__i0__DOT__lut;
        IData/*31:0*/ top__DOT__u2__DOT__u2__DOT__u1__DOT__i0__DOT__lut_out;
        IData/*31:0*/ top__DOT__u3__DOT__ALUIn1;
        IData/*31:0*/ top__DOT__u3__DOT__ALUIn2;
        IData/*31:0*/ top__DOT__u3__DOT__ALUResult;
        IData/*31:0*/ top__DOT__u3__DOT__M_rdatatoReg;
        IData/*31:0*/ top__DOT__u3__DOT__ALUIn1MUX__DOT__i0__DOT__lut_out;
        IData/*31:0*/ top__DOT__u3__DOT__ALUIn2MUX__DOT__i0__DOT__lut_out;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__ADDERIn2;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__ADDSUBADDERIn2;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__ADDSUBResult;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__SHIFTResult;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__LOGICResult;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__SUBMux__DOT__i0__DOT__lut_out;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__ADDERIn2MUX__DOT__i0__DOT__lut_out;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__COMPResultMUX__DOT__i0__DOT__lut;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__lvl1;
    };
    struct {
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__lvl2;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__lvl3;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__lvl4;
        VlWide<5>/*135:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u1__DOT__i0__DOT__lut;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u1__DOT__i0__DOT__lut_out;
        VlWide<5>/*135:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u2__DOT__i0__DOT__lut;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u2__DOT__i0__DOT__lut_out;
        VlWide<5>/*135:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u3__DOT__i0__DOT__lut;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u3__DOT__i0__DOT__lut_out;
        VlWide<5>/*135:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u4__DOT__i0__DOT__lut;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u4__DOT__i0__DOT__lut_out;
        VlWide<5>/*135:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u5__DOT__i0__DOT__lut;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u5__DOT__i0__DOT__lut_out;
        VlWide<4>/*104:0*/ top__DOT__u3__DOT__ALU__DOT__LogicModule__DOT__i0__DOT__lut;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__LogicModule__DOT__i0__DOT__lut_out;
        VlWide<5>/*131:0*/ top__DOT__u3__DOT__ALU__DOT__ResultMux__DOT__i0__DOT__lut;
        IData/*31:0*/ top__DOT__u3__DOT__ALU__DOT__ResultMux__DOT__i0__DOT__lut_out;
        IData/*31:0*/ top__DOT__u3__DOT__M_rdataMUX__DOT__i0__DOT__lut_out;
        VlWide<5>/*135:0*/ top__DOT__u3__DOT__RegInMUX__DOT__i0__DOT__lut;
        IData/*31:0*/ top__DOT__u3__DOT__RegInMUX__DOT__i0__DOT__lut_out;
        IData/*31:0*/ top__DOT__u3__DOT__BranchMUX__DOT__i0__DOT__lut_out;
        IData/*31:0*/ top__DOT__u5__DOT__rlen_num;
        IData/*31:0*/ top__DOT__u5__DOT__wlen_num;
        IData/*31:0*/ top__DOT__u5__DOT__u0__DOT__i0__DOT__lut_out;
        IData/*31:0*/ top__DOT__u5__DOT__u1__DOT__i0__DOT__lut_out;
        IData/*31:0*/ __Vfunc_top__DOT__u5__DOT__vaddr_read__6__Vfuncout;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_4;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_5;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_8;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_9;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_17;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_18;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_19;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_20;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_21;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_31;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_32;
        IData/*31:0*/ __VactIterCount;
        QData/*32:0*/ __VdfgRegularize_h6e95ff9d_0_11;
        QData/*32:0*/ __VdfgRegularize_h6e95ff9d_0_15;
        QData/*32:0*/ __VdfgRegularize_h6e95ff9d_0_23;
        QData/*32:0*/ __VdfgRegularize_h6e95ff9d_0_27;
        VlUnpacked<IData/*31:0*/, 16> top__DOT__u0__DOT__rf;
        VlUnpacked<SData/*8:0*/, 3> top__DOT__u2__DOT__u0__DOT__BranchEnc__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*6:0*/, 3> top__DOT__u2__DOT__u0__DOT__BranchEnc__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*1:0*/, 3> top__DOT__u2__DOT__u0__DOT__BranchEnc__DOT__i0__DOT__data_list;
        VlUnpacked<CData/*7:0*/, 1> top__DOT__u2__DOT__u0__DOT__isB_typeEnc__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*6:0*/, 1> top__DOT__u2__DOT__u0__DOT__isB_typeEnc__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*0:0*/, 1> top__DOT__u2__DOT__u0__DOT__isB_typeEnc__DOT__i0__DOT__data_list;
        VlUnpacked<SData/*8:0*/, 4> top__DOT__u2__DOT__u0__DOT__RegInEnc__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*6:0*/, 4> top__DOT__u2__DOT__u0__DOT__RegInEnc__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*1:0*/, 4> top__DOT__u2__DOT__u0__DOT__RegInEnc__DOT__i0__DOT__data_list;
        VlUnpacked<CData/*7:0*/, 2> top__DOT__u2__DOT__u0__DOT__ALUIn1SelEnc__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*6:0*/, 2> top__DOT__u2__DOT__u0__DOT__ALUIn1SelEnc__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*0:0*/, 2> top__DOT__u2__DOT__u0__DOT__ALUIn1SelEnc__DOT__i0__DOT__data_list;
        VlUnpacked<CData/*7:0*/, 2> top__DOT__u2__DOT__u0__DOT__ALUIn2SelEnc__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*6:0*/, 2> top__DOT__u2__DOT__u0__DOT__ALUIn2SelEnc__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*0:0*/, 2> top__DOT__u2__DOT__u0__DOT__ALUIn2SelEnc__DOT__i0__DOT__data_list;
        VlUnpacked<CData/*7:0*/, 7> top__DOT__u2__DOT__u0__DOT__R_wenEnc__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*6:0*/, 7> top__DOT__u2__DOT__u0__DOT__R_wenEnc__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*0:0*/, 7> top__DOT__u2__DOT__u0__DOT__R_wenEnc__DOT__i0__DOT__data_list;
        VlUnpacked<CData/*7:0*/, 1> top__DOT__u2__DOT__u0__DOT__M_renEnc__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*6:0*/, 1> top__DOT__u2__DOT__u0__DOT__M_renEnc__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*0:0*/, 1> top__DOT__u2__DOT__u0__DOT__M_renEnc__DOT__i0__DOT__data_list;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 1> top__DOT__u2__DOT__u0__DOT__M_wenEnc__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*6:0*/, 1> top__DOT__u2__DOT__u0__DOT__M_wenEnc__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*0:0*/, 1> top__DOT__u2__DOT__u0__DOT__M_wenEnc__DOT__i0__DOT__data_list;
        VlUnpacked<CData/*7:0*/, 1> top__DOT__u2__DOT__u0__DOT__EandCSREnc__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*6:0*/, 1> top__DOT__u2__DOT__u0__DOT__EandCSREnc__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*0:0*/, 1> top__DOT__u2__DOT__u0__DOT__EandCSREnc__DOT__i0__DOT__data_list;
        VlUnpacked<IData/*25:0*/, 1> top__DOT__u2__DOT__u1__DOT__u0__DOT__i0__DOT__pair_list;
        VlUnpacked<IData/*24:0*/, 1> top__DOT__u2__DOT__u1__DOT__u0__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*0:0*/, 1> top__DOT__u2__DOT__u1__DOT__u0__DOT__i0__DOT__data_list;
        VlUnpacked<CData/*5:0*/, 2> top__DOT__u2__DOT__u2__DOT__u0__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*0:0*/, 2> top__DOT__u2__DOT__u2__DOT__u0__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*4:0*/, 2> top__DOT__u2__DOT__u2__DOT__u0__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*38:0*/, 9> top__DOT__u2__DOT__u2__DOT__u1__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*6:0*/, 9> top__DOT__u2__DOT__u2__DOT__u1__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 9> top__DOT__u2__DOT__u2__DOT__u1__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*32:0*/, 2> top__DOT__u3__DOT__ALUIn1MUX__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*0:0*/, 2> top__DOT__u3__DOT__ALUIn1MUX__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 2> top__DOT__u3__DOT__ALUIn1MUX__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*32:0*/, 2> top__DOT__u3__DOT__ALUIn2MUX__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*0:0*/, 2> top__DOT__u3__DOT__ALUIn2MUX__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 2> top__DOT__u3__DOT__ALUIn2MUX__DOT__i0__DOT__data_list;
        VlUnpacked<CData/*1:0*/, 3> top__DOT__u3__DOT__ALU__DOT__u0__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*0:0*/, 3> top__DOT__u3__DOT__ALU__DOT__u0__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*0:0*/, 3> top__DOT__u3__DOT__ALU__DOT__u0__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*32:0*/, 2> top__DOT__u3__DOT__ALU__DOT__SUBMux__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*0:0*/, 2> top__DOT__u3__DOT__ALU__DOT__SUBMux__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 2> top__DOT__u3__DOT__ALU__DOT__SUBMux__DOT__i0__DOT__data_list;
        VlUnpacked<CData/*1:0*/, 2> top__DOT__u3__DOT__ALU__DOT__u1__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*0:0*/, 2> top__DOT__u3__DOT__ALU__DOT__u1__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*0:0*/, 2> top__DOT__u3__DOT__ALU__DOT__u1__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*32:0*/, 2> top__DOT__u3__DOT__ALU__DOT__ADDERIn2MUX__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*0:0*/, 2> top__DOT__u3__DOT__ALU__DOT__ADDERIn2MUX__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 2> top__DOT__u3__DOT__ALU__DOT__ADDERIn2MUX__DOT__i0__DOT__data_list;
        VlUnpacked<CData/*3:0*/, 8> top__DOT__u3__DOT__ALU__DOT__COMPResultMUX__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*2:0*/, 8> top__DOT__u3__DOT__ALU__DOT__COMPResultMUX__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*0:0*/, 8> top__DOT__u3__DOT__ALU__DOT__COMPResultMUX__DOT__i0__DOT__data_list;
        VlUnpacked<CData/*2:0*/, 1> top__DOT__u3__DOT__ALU__DOT__u2__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*1:0*/, 1> top__DOT__u3__DOT__ALU__DOT__u2__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*0:0*/, 1> top__DOT__u3__DOT__ALU__DOT__u2__DOT__i0__DOT__data_list;
        VlUnpacked<CData/*1:0*/, 2> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u0__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*0:0*/, 2> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u0__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*0:0*/, 2> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u0__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*33:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u1__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*1:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u1__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u1__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*33:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u2__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*1:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u2__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u2__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*33:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u3__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*1:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u3__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u3__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*33:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u4__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*1:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u4__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u4__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*33:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u5__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*1:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u5__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ShiftModule__DOT__u5__DOT__i0__DOT__data_list;
        VlUnpacked<CData/*3:0*/, 3> top__DOT__u3__DOT__ALU__DOT__u3__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*2:0*/, 3> top__DOT__u3__DOT__ALU__DOT__u3__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*0:0*/, 3> top__DOT__u3__DOT__ALU__DOT__u3__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*34:0*/, 3> top__DOT__u3__DOT__ALU__DOT__LogicModule__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*2:0*/, 3> top__DOT__u3__DOT__ALU__DOT__LogicModule__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 3> top__DOT__u3__DOT__ALU__DOT__LogicModule__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*32:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ResultMux__DOT__i0__DOT__pair_list;
    };
    struct {
        VlUnpacked<CData/*0:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ResultMux__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 4> top__DOT__u3__DOT__ALU__DOT__ResultMux__DOT__i0__DOT__data_list;
        VlUnpacked<CData/*3:0*/, 3> top__DOT__u3__DOT__M_rlenMUX__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*1:0*/, 3> top__DOT__u3__DOT__M_rlenMUX__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*1:0*/, 3> top__DOT__u3__DOT__M_rlenMUX__DOT__i0__DOT__data_list;
        VlUnpacked<CData/*3:0*/, 3> top__DOT__u3__DOT__M_wlenMUX__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*1:0*/, 3> top__DOT__u3__DOT__M_wlenMUX__DOT__i0__DOT__key_list;
        VlUnpacked<CData/*1:0*/, 3> top__DOT__u3__DOT__M_wlenMUX__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*34:0*/, 2> top__DOT__u3__DOT__M_rdataMUX__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*2:0*/, 2> top__DOT__u3__DOT__M_rdataMUX__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 2> top__DOT__u3__DOT__M_rdataMUX__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*33:0*/, 4> top__DOT__u3__DOT__RegInMUX__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*1:0*/, 4> top__DOT__u3__DOT__RegInMUX__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 4> top__DOT__u3__DOT__RegInMUX__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*33:0*/, 3> top__DOT__u3__DOT__BranchMUX__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*1:0*/, 3> top__DOT__u3__DOT__BranchMUX__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 3> top__DOT__u3__DOT__BranchMUX__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*33:0*/, 3> top__DOT__u5__DOT__u0__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*1:0*/, 3> top__DOT__u5__DOT__u0__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 3> top__DOT__u5__DOT__u0__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*33:0*/, 3> top__DOT__u5__DOT__u1__DOT__i0__DOT__pair_list;
        VlUnpacked<CData/*1:0*/, 3> top__DOT__u5__DOT__u1__DOT__i0__DOT__key_list;
        VlUnpacked<IData/*31:0*/, 3> top__DOT__u5__DOT__u1__DOT__i0__DOT__data_list;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
        VlUnpacked<CData/*0:0*/, 5> __Vm_traceActivity;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
